[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "api-docs/_build/html"
  command = "cd api-docs && make clean html && cd .."

[context.production]
  publish = "api-docs/_build/html"
  command = "cd api-docs && make clean html && cd .."

[context.deploy-preview]
  publish = "api-docs/_build/html"
  command = "cd api-docs && make clean html && cd .."

[[redirects]]
  from = "/*"
  to = "/docs/dedicated-load-balancers/v2/:splat"
  status = 301
  force = false